### ISSUE TITLE
FSX crashes when it cannot open disk image

### ISSUE THREAD

**Issue by pixitha** [kgober/FSX#1]
I was attempting to open a dsk file that was already in use by Simh, it would be nice if it just printed the error, but didn't crash. Not sure if its an easy fix or not.

```
FSX>mount d0 tcpipm.dsk

Unhandled Exception: System.IO.IOException: The process cannot access the file 'D:\pdp11-fuzzball\tcpipm.dsk' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.ReadAllBytes(String path)
   at FSX.HostFS.ReadFile(String fileSpec) in C:\Users\kgober\Personal\Code\FSX\HostFS.cs:line 203
   at FSX.Program.LoadFS(String source, List`1 opts) in C:\Users\kgober\Personal\Code\FSX\Program.cs:line 588
   at FSX.Program.CommandLoop(TextReader input) in C:\Users\kgober\Personal\Code\FSX\Program.cs:line 245
   at FSX.Program.Main(String[] args) in C:\Users\kgober\Personal\Code\FSX\Program.cs:line 152
PS D:\fsx\bin>
```

**Comment by kgober** [comment]
It's an easy-ish fix.  The latest commit will now display an error message, which is easy.  Then FSX will lie to you and tell you the file is empty.  Fixing that is less easy so I'll leave it.  Hopefully people will be able to guess that "Empty File" is because of the error.
